### ISSUE TITLE
Some sus things

### ISSUE THREAD

**Issue by TheRealOmitron** [PizzaboiBestLegit/Pizza-Client#1]
I do not believe this to be a virus but can you please tell me wtf is in assets.pizzaclient? Also what is with all the arab stuff. 7/10 Rated. I would have used if not for all the wierd stuff in it.

**Comment by PizzaboiBestLegit** [comment]
bro tf u on lmao

**Comment by smreith** [comment]
its a fucking joke i see no problem with it
