### ISSUE TITLE
Make a sound for auto sniper

### ISSUE THREAD

**Issue by UltimateBoi** [PizzaboiBestLegit/Pizza-Client#13]

**Comment by UltimateBoi** [comment]
also make it account for tax

**Comment by UltimateBoi** [comment]
also make an option to prioritize titanium in mithril macro options

**Comment by UltimateBoi** [comment]
also make an option to disable the arab text when you are loading into the game and stuf. Troll face is ok but i kinda wana see whats loading cuz i make modz

**Comment by PizzaboiBestLegit** [comment]
> also make an option to prioritize titanium in mithril macro options

isn't there a setting for it? or does it not work

**Comment by UltimateBoi** [comment]
yes but also just add the code 

```

                                    (Minecraft.getMinecraft()).thePlayer.playSound("random.orb", 2.0F, 1.0F);
```
for the sound in auto snipe

**Comment by PizzaboiBestLegit** [comment]
alr did

**Comment by UltimateBoi** [comment]
ok cool now release
