### ISSUE TITLE
Another ratted version of pizza https://github.com/HypixelQOL/Pizza

### ISSUE THREAD

**Issue by UltimateBoi** [PizzaboiBestLegit/Pizza-Client#14]
[This is the ratted one](https://github.com/HypixelQOL/Pizza) that "HypixelQOL" made

DONT DOWNLOAD it 
It uses all the common stuff like reflxcion and shit

also this whole guys github repos are just common QOL mods but with rats...

**Comment by SkyZ1412** [comment]
thanks bro

**Comment by MrDev139** [comment]
Its taken down well done guys

**Comment by idontgetcoins** [comment]
is there anything i can do i installed it and i don't know if there is a way i can stop it or my accoutn is gone and also do you know where to fine the legit one

**Comment by UltimateBoi** [comment]
this is the legit one
