### ISSUE TITLE
Need help with starting the client 

### ISSUE THREAD

**Issue by Zabbala** [PizzaboiBestLegit/Pizza-Client#18]
After I download the .jar file I can't seem to do anything with it. do i have to download anything else to get it to work

**Comment by tiesdf** [comment]
just put it in your mods folder

**Comment by Zabbala** [comment]
> just put it in your mods folder

Quick question why does it say Qol mods? isn't he the one who rats accounts?

**Comment by UltimateBoi** [comment]
cuz its quality of like mods...

**Comment by KimBapX** [comment]
yo y is pizzaclient mod id pizzaclient. gonna look sus for me wtf man

**Comment by UltimateBoi** [comment]
cuz it is lol

**Comment by Zabbala** [comment]
im retarded I just thought of the YouTuber who is a rat and his name was QOL and I forgot what it means but when you open the client it has a fire opening lmao

**Comment by PizzaboiBestLegit** [comment]
> yo y is pizzaclient mod id pizzaclient. gonna look sus for me wtf man

it hides modid
