### ISSUE TITLE
Rat

### ISSUE THREAD

**Issue by Skyblocksupdragnon** [PizzaboiBestLegit/Pizza-Client#2]
Is this a rat or not? It loaded up with something weird.

**Comment by vov4ikrobo** [comment]
It is rat, i got hacked and lost 2b, also i got banned

**Comment by PizzaboiBestLegit** [comment]
yes big rat

**Comment by RedaxMst** [comment]
is:issue is:open i uset Piza client (download it from Link of QOL channel ) and after 2 weeks every single item gone so you putting ratted versions bro i lost 3b cause of you @PizzaboiBestLigit  plz contact me in discord REDAX#1966 lets make a deal :)
