### ISSUE TITLE
In my research it's not a rat

### ISSUE THREAD

**Issue by ergs0204** [PizzaboiBestLegit/Pizza-Client#22]
I know there's a post about the issue, but i use some other method to confirm it.
The post : https://github.com/PizzaboiBestLegit/Pizza-Client/issues/8

After decompiling it, I try to find all url in it. All urls are in "QolSkyblockMod/PizzaClient/features/misc/AutoFlipper.java" , "QolSkyblockMod/PizzaClient/PizzaClient.java" , "QolSkyblockMod/PizzaClient/commands/ArabFunnyCommand.java:"

First one is for gathering flipping data. And every links are fine as in thread mentioned.

Second : https://gist.githubusercontent.com/PizzaboiBestLegit/e86e41c230949e51309c621548be55aa/raw/pizzaclien
The link seem weird at first, but is just json data.

Third one is just some youtube links.

What i did more than the thread mentioned.

I also check if there's encrypted string for other weird purpose but find none.

For the autoupdate the file is exactly the same after checking hash (the update version might be modified after), but for now, it's safe.

p.s. why not make it opensorce so that everyone can use it more confidently.

**Comment by Zabbala** [comment]
pog

**Comment by PizzaboiBestLegit** [comment]
yk you can just decompile and check the code
