### ISSUE TITLE
Gemstone Nuker does not mine glass pane gems

### ISSUE THREAD

**Issue by jbgray5** [PizzaboiBestLegit/Pizza-Client#24]
gemstone nuker does not break the glass pane gems in the crystal hollows

**Comment by PizzaboiBestLegit** [comment]
yea bc mining those is literally 50% less gems

**Comment by jbgray5** [comment]
> yea bc mining those is literally 50% less gems or smth like that

its a lot faster than going all the way to a new vein, so would still be really helpful if it mined them as there are usually more panes than there are full blocks

**Comment by PizzaboiBestLegit** [comment]
i'll just add a toggle for it ig
