### ISSUE TITLE
Does the client still work? Will you get watchdogged as soon as you join?

### ISSUE THREAD

**Issue by notKassi** [PizzaboiBestLegit/Pizza-Client#25]
Honestly i got yeared on my main after trying out a client. It was as soon as i logged in so im guessing it was the client i was using so im pretty sketched out to new clients. Can I still use this without getting banned?

**Comment by Daeinkord** [comment]
There is nothing that blatant that will instantly ban you. So yes, you can use it without getting banned instantly.

**Comment by PizzaboiBestLegit** [comment]
nothing but crop aura bans. Next release has a fixed version of crop aura that doesn't ban btw
