### ISSUE TITLE
auto mithril work ? do you have discord is not working on mine !!

### ISSUE THREAD

**Issue by arnaudjolivier** [PizzaboiBestLegit/Pizza-Client#26]

**Comment by arnaudjolivier** [comment]
when i use nuker on mithril my head dont move how to move it ?

**Comment by PizzaboiBestLegit** [comment]
what

**Comment by arnaudjolivier** [comment]
Can u do a video for mithril macro because mine dont work or can u add me on discord ?

**Comment by arnaudjolivier** [comment]
Because i setup the macro mining but nothing happened when i press the keybind its writting macro activated and nothing happen

**Comment by PizzaboiBestLegit** [comment]
it worked for everyone else, r u using nuker or macro?

**Comment by jbgray5** [comment]
make sure mithril macro is selected, then click F when your near some mithril

**Comment by arnaudjolivier** [comment]
its what i did but its not working

**Comment by arnaudjolivier** [comment]
only work on hypixel ?
or other server also ?

**Comment by arnaudjolivier** [comment]
i try macro but not working and nuker working but not on hypixel

**Comment by PizzaboiBestLegit** [comment]
it worked for everyone else so i have no idea
