### ISSUE TITLE
i need help using the mithril macro

### ISSUE THREAD

**Issue by Co18** [PizzaboiBestLegit/Pizza-Client#29]
i cant understand how to activate the mithril macro there is no button to enable it and i dont understand how the keybind thing works

**Comment by PizzaboiBestLegit** [comment]
go in config, search "macro key", change it to mithril then press the macro keybind

**Comment by Co18** [comment]
how do i change the keybind ? ? ? ? ? ? ?

isnt there any easier option to active the mithril bot or im just blind and dumb

**Comment by tiesdf** [comment]
holy frick just go to control settings in minecraft npc

**Comment by hafa-alt** [comment]
hello i cant figure out what the config is plz help me
