### ISSUE TITLE
Suggestion: Failsafe

### ISSUE THREAD

**Issue by TreXito** [PizzaboiBestLegit/Pizza-Client#31]
When player is near chitr, chitr uncrouches, takes out sb menu to look like he opened it very good yes

**Comment by Skyblocksupdragnon** [comment]
Do you know how to spell .

**Comment by PizzaboiBestLegit** [comment]
chitr?

**Comment by jbgray5** [comment]
> chitr?

i think he means cheater, when player is near cheater you pull out sb menu
