### ISSUE TITLE
update when

### ISSUE THREAD

**Issue by jbgray5** [PizzaboiBestLegit/Pizza-Client#32]

**Comment by PizzaboiBestLegit** [comment]
not sure yet, need to fix stuff

**Comment by MrDev139** [comment]
this is github you're supposed to make it open source lol

**Comment by PizzaboiBestLegit** [comment]
who says that?

**Comment by UltimateBoi** [comment]
@PizzaboiBestLegit 
![image](https://user-images.githubusercontent.com/63293118/151712936-1dc2c255-698b-4cbe-b88c-6172a1c560f1.png)
flipper buggin (ik its wip but just work on it pls ;p;)

**Comment by johndoe812** [comment]
@PizzaboiBestLegit 
sorry if this is a stupid question but how do you build the farm that makes the "s shaped farm" macro work?

**Comment by UltimateBoi** [comment]
bruh

**Comment by johndoe812** [comment]
> bruh

mb i got it already

**Comment by UltimateBoi** [comment]
lol

**Comment by PizzaboiBestLegit** [comment]
> @PizzaboiBestLegit ![image](https://user-images.githubusercontent.com/63293118/151712936-1dc2c255-698b-4cbe-b88c-6172a1c560f1.png) flipper buggin (ik its wip but just work on it pls ;p;)

idk effort
