### ISSUE TITLE
command

### ISSUE THREAD

**Issue by kadenyaboi** [PizzaboiBestLegit/Pizza-Client#33]
create a command to start the macro, instead of a keybind. Also add a start macro on reconnect feature

**Comment by PizzaboiBestLegit** [comment]
why?

**Comment by kadenyaboi** [comment]
> why?

So with some auto reconnect mods, they run a command when it rejoins. I can't find a auto rc mod that presses a key, but I can find ones that send a chat message or run a command. When hypixel kicks for server reboot, it disconnects, turning off the macro, when I rejoin the macro is off. I have auto commands setup to reput me in skyblock on my island just nothing to start the macro again

**Comment by kadenyaboi** [comment]
> why?

You could also keep the keybind to start a macro and just add a command as a second option

**Comment by PizzaboiBestLegit** [comment]
next release has auto reconnect and auto join skyblock so yea
