### ISSUE TITLE
commision macro doesn´t work

### ISSUE THREAD

**Issue by justelus1** [PizzaboiBestLegit/Pizza-Client#40]
so it uses the pidgeon swaps to a aotv sneak and nothing else happens
also keep focus while being tabbed out doesn´t work

**Comment by Dexter167** [comment]
do u have a aotv?

**Comment by NoobifiedBestLegit** [comment]
aotv must have ether teleportation with a 61 block

**Comment by Dexter167** [comment]
well rip cant afford aotv 😢

**Comment by justelus1** [comment]
it is a 61 block aotv

**Comment by justelus1** [comment]
now it kinda works as long as im sneaking
