### ISSUE TITLE
mithril macro aotv not working

### ISSUE THREAD

**Issue by idkrandomperson** [PizzaboiBestLegit/Pizza-Client#41]
doesnt tp back with aotv when i get warped out from lobby while mithril macroing
Pizza> Something went wrong with the AOTV Movement, trying again (21)

**Comment by NoobifiedBestLegit** [comment]
aotv must have ether teleportation with a 61 block

**Comment by idkrandomperson** [comment]
> aotv must have ether teleportation with a 61 block
oh ok then ty
