### ISSUE TITLE
1.1.1 Doesnt Load

### ISSUE THREAD

**Issue by BioVC** [PizzaboiBestLegit/Pizza-Client#46]
i put it in the mods folder and everything's fine then it just crashes i have no idea why, i would love some help

**Comment by kads-e** [comment]
sounds like a u problem, maybe send a screenshot of the modfolder, maybe theres something wrong with it. Also has it worked befor or did u ever use any mods?

**Comment by BioVC** [comment]
only previous versions work, adn ye s i use other mods aswell

**Comment by BioVC** [comment]
![image](https://user-images.githubusercontent.com/99313938/153530479-de2a4dc4-f3f9-4bfe-b840-68a3551c658d.png)

**Comment by BioVC** [comment]
![image](https://user-images.githubusercontent.com/99313938/153530509-8ddd0d65-405f-450a-89cd-276dbb29ff56.png)

**Comment by PizzaboiBestLegit** [comment]
send crash report

**Comment by BioVC** [comment]
![image](https://user-images.githubusercontent.com/99313938/153681188-394f4524-04d1-4e6e-bc32-52a3fac10375.png)

**Comment by PizzaboiBestLegit** [comment]
levelhead, sone versions work but some don't idk

**Comment by BioVC** [comment]
thank you, it works now :D
