### ISSUE TITLE
There's another guy that modified this client

### ISSUE THREAD

**Issue by MrDev139** [PizzaboiBestLegit/Pizza-Client#5]
There's another guy that modified your client and add some shitty code to gain access to other accounts and hack them
https://github.com/PizzaBoi9/Pizza_Client-1.1-Public
Already reported
I decompiled the client and it got the fellowing :
1-Discord Token grabber
2-Session ID stealer (Might allow them to login to your mc account without your password)
3-It searches for more than just the discord token it also searches for your payment methods like your credit card and it gets more info about your account
4-It steals the saved account on your launcher via the the launcher_accounts.json file
5-It also targets chrome default profile and searches for your data
6-It takes a screenshot of your desktop and sends it to them
7-it gets your mods and sends them to him (weird)
8-It gets your IP + your hardware and system information and sends it to them
9-For some reason it searchs in the downloads directory for a jar file that is less than 7MB and it sends it to them(very weird)
10-For some reason there is a string array with base64 encoded webhook links(5 links) that all are the same and dead anyway
NOTE:it sends all the grabbed and collected data via a discord webhook which apparently is dead

**Comment by PizzaboiBestLegit** [comment]
yea i'm aware, sadly i can't do anything against those.

**Comment by saepojsekpi** [comment]
7 and 9 are probably so he can get more cheats to use for himself or to rat and "leak" on github

**Comment by MrDev139** [comment]
> yea i'm aware, sadly i can't do anything against those.
Report his account at least for malware content or phishing or whatever

**Comment by annguyentv** [comment]
How can you check it so detail?

**Comment by saepojsekpi** [comment]
it got shut down lets go.

**Comment by MrDev139** [comment]
let's gooo
