### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by NickT596** [PizzaboiBestLegit/Pizza-Client#53]
![image](https://user-images.githubusercontent.com/91540164/153863923-07fee869-3b1d-4463-9fe5-062f8d497534.png)

this prob i have when use pizza client newest version
D:

**Comment by Dexter167** [comment]
@PizzaboiBestLegit  This is no problem with ur mods, it is other mods trying to connect to hypixel servers like neu to get hypixel info etc...

**Comment by PizzaboiBestLegit** [comment]
the thing is that it should work fine tho
