### ISSUE TITLE
HACKED CLIENT

### ISSUE THREAD

**Issue by DanyeG** [PizzaboiBestLegit/Pizza-Client#55]
Do not install this shi. I got hacked and my friend got beamed on his discord and hypixel accounts.

**Comment by smreith** [comment]
Skill issue be like:

**Comment by justelus1** [comment]
i didnt and also be happy you no longer have to play this game he freeded your addiction

**Comment by justelus1** [comment]
also learn to check what mod are rats you prob downloaded some other rat

**Comment by PizzaboiBestLegit** [comment]
yea....
