### ISSUE TITLE
Suggestion Divan Mine Macro

### ISSUE THREAD

**Issue by xXtomtoXx** [PizzaboiBestLegit/Pizza-Client#57]
Hello it is me again
I was curious if it was possible for you to consider adding a divan mine macro to automatically collect the chests with the metal detector.

Thanks for providing this nice Mod btw

**Comment by cuteacc** [comment]
NotEnoughUpdates mod has something similar to this where it marks possible locations and the correct location as you move closer.

**Comment by xXtomtoXx** [comment]
> NotEnoughUpdates mod has something similar to this where it marks possible locations and the correct location as you move closer.

That I am aware of the point being if you were to create auto pathfinding to the correct spot and make it auto collect that would be nice wouldn’t it?

**Comment by PizzaboiBestLegit** [comment]
maybe in the future
