### ISSUE TITLE
patcher incompabibility

### ISSUE THREAD

**Issue by throwoway3** [PizzaboiBestLegit/Pizza-Client#58]
when using pizza with patcher, both on latest versions (1.8.0 Patcher and 1.1.2-pre1 Pizza), the background shadow feature to disable the chat background stops working in patcher. only pizza is causing this issue, tested it myself.

**Comment by justelus1** [comment]
yep noticed it atwell but i didnt care

**Comment by PizzaboiBestLegit** [comment]
use pizza clear chat, if u don't have it make sure u have pre1.2 installed
