### ISSUE TITLE
im getting crashed

### ISSUE THREAD

**Issue by SDGAce** [PizzaboiBestLegit/Pizza-Client#65]
every time i open the macro page it crashes me

**Comment by PizzaboiBestLegit** [comment]
close minecraft, go to .minecraft/config/pizzaclient/config.toml, open it in notepad, search for macro_keybind, set it to any number between 0 and 8, save it and try again. If that doesn't work, delete the config.toml file. That will reset all your config but it fixes 100% of the time.

**Comment by SDGAce** [comment]
thx that worked
