### ISSUE TITLE
getting sent to lobby

### ISSUE THREAD

**Issue by juniorwastaken** [PizzaboiBestLegit/Pizza-Client#67]
When using the commision macro I end up in hypixel lobby after around 30 minutes. I noticed that whenever it happens its after opening pigeon, but before claiming the commision.

**Comment by SkyblockModsS** [comment]
Did u find a fix? I found one I think. msg me if u want a fix. ToadallyAwesome#8476

**Comment by juniorwastaken** [comment]
the last patch fixed it for me
