### ISSUE TITLE
For people that don't trust the client or think its a rat

### ISSUE THREAD

**Issue by pyrohyro** [PizzaboiBestLegit/Pizza-Client#8]
The mod seems to be clean I'll be buying a new minecraft account tomorrow and testing it out more
and use an http spy.

these are the only urls that are used by the mod that I found
https://sbe-stole-skytils.design/api/auctions/lowestbins -- safe from skytils 
url from: https://github.com/Skytils/SkytilsMod/blob/d0fdb1a49c65f25a73c7d7a59795c7e4797cdac0/src/main/kotlin/skytils/skytilsmod/features/impl/handlers/AuctionData.kt 
url directory on this mod: PizzaClient/QolSkyblockMod.PizzaClient/features/misc/AutoFlipper.class

https://moulberry.codes/auction_averages/3day.json
url from: too lazy to find but look at the url bro its from moulberry
url directory on this mod: PizzaClient/QolSkyblockMod.PizzaClient/features/misc/AutoFlipper.class

https://api.hypixel.net/skyblock/auctions?page=0
url from: hypickle
url directory on this mod: PizzaClient/QolSkyblockMod.PizzaClient/features/misc/AutoFlipper.class

bruh he made an AI for mining idk if it works but that shit is cool.

https://gist.githubusercontent.com/PizzaboiBestLegit/e86e41c230949e51309c621548be55aa/raw/pizzaclient
an updater
this looks kinda sus though might be a different version of pizzaclient I haven't searched it for a logger yet so idk
also found this inside it cheaters.get.banned.remote.Analytics dunno what it means

found this on util/misc/RatException.class

package QolSkyblockMod.PizzaClient.util.misc;
import QolSkyblockMod.PizzaClien.util.Utils;
public class RatException extends RuntimeException {
	public RatException() {
		super(Utils.getExecutor() + " is a rat.");
	}
}

if you want to find what urls its accessing without using a decompiler and looking for them yourself
open cmd promt 
run ipconfig/flushdns
then start minecraft
join skyblock
run ipconfig/displaydns
and try to find any sus urls
there might be trackers from your browser 
they did not come from the mod 
make sure to search up the url in google just to be sure

make sure to close browsers and other applications that uses the internet
so you wouldn't be confused if its just a tracker on a website in your browser
or if its the one from the mod itself

**Comment by pyrohyro** [comment]
ok so I just checked the file size of the updater thing
they both have the same exact file size so Its probably safe too

**Comment by MrDev139** [comment]
for me it seemed safe

**Comment by UltimateBoi** [comment]
it is safe.

**Comment by Sloppycoco** [comment]
It's a rat lmfao

**Comment by UltimateBoi** [comment]
? its not
