### ISSUE TITLE
Goblin esp doesn't disable on goblins that aren't named "Goblin"

### ISSUE THREAD

**Issue by RectangularObject** [PizzaboiBestLegit/Pizza-Client#9]
Knifethrowers, Fireslingers, Weaklings, every goblin in the goblin raid event, always have the esp rendered on them, regardless of the goblin esp setting.

**Comment by RectangularObject** [comment]
![2021-12-31_01 53 02](https://user-images.githubusercontent.com/26125768/147810617-a6d26257-c96c-491d-acaf-ff77268fda8e.png)

**Comment by PizzaboiBestLegit** [comment]
i'm aware, will be fixed next version
